theme-color: #B5E853
title: The Converter
description: Converts your account's DBID into a close approximation of your account creation date
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
